### ISSUE TITLE
A quick question about tutorial on your blog

### ISSUE THREAD

**Issue by jiajiayb** [ischlag/tensorflow-input-pipelines#1]
A quick question, I run into "Enqueue operation was cancelled" errors by running the example here (http://ischlag.github.io/2016/11/07/tensorflow-input-pipeline-for-large-datasets/). Do you mean this is not a problem? If not, how could we fix this. Thanks!﻿

**Comment by ischlag** [comment]
Foremost, the code was written for 0.8.0 so take it with a grain of salt. There is also some stuff that doesn't belong here but I didn't clean up the repo yet. The enqueue operation was cancelled is not problematic and more of a warning than an error. It is due to the python threads still running and trying to enqueue into the tensorflow queue using a session after you have closed the session at the end of your script. Solution: you can make the while loop in the enqueue function which is run by a python thread stoppable and then manually stop these threads before closing the queue and the tensorflow session.
